export const INITIAL_DATA = [
  {
    id: 'de4rgere',
    product_name: '1',
    price: 4,
    description: 'dddd',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'ef5ed7js',
    product_name: '2',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'ef54ddjs',
    product_name: '3',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'efeek7j5',
    product_name: '4',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'fdsfrrtf',
    product_name: '5',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'ffr4d7js',
    product_name: '6',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'fewewdsf',
    product_name: '7',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'hfr4d7js',
    product_name: '8',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'fewffewf',
    product_name: '9',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
  {
    id: 'd4d4dsdd',
    product_name: '10',
    price: 4,
    description: 'fff',
    createdAt: '07/Mo/2022',
  },
]
